//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTCDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_H
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ItemDes { get; set; }
        public Nullable<int> ItemTax { get; set; }
        public Nullable<int> ItemPrice { get; set; }
        public Nullable<int> ItemDiscount { get; set; }
    }
}
